---
subtitle: "MA8701 Advanced Statistical Learning V2023"
title: "Compulsory exercise: Team Supergreat"
author: "Nora Aasen, Elias Angelsen, Jonas Nordstr?m"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document
  # pdf_document
---
  
```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE,tidy=TRUE,message=FALSE,warning=FALSE,strip.white=TRUE,prompt=FALSE,
                      cache=TRUE, size="scriptsize",
                      fig.width=4, fig.height=3,fig.align = "center")
```


# Setup

```{r Loading Packages,eval=TRUE,echo=FALSE}
# Load libraries
library(naniar)
library(mice)
library(glmnet)
library(dplyr)
library(caret)
```

## Exploratory Analysis
```{r Loading Data}
# Load and look at data
data <- read.csv("framingham.csv")
head(data)
md.pattern(data)
gg_miss_var(data)

# Make a dataset containing only the complete cases
df_complete <- data[complete.cases(data), ]
dim(df_complete)

# Should we code the binary responses to be categorical instead of integers? 
# Education should be categorical
```
## Missing Data

# Model

## Naive Approach
```{r Logistic Model}
# Fit a logistic model
mod0 <- glm(TenYearCHD ~ ., data = df_complete, family = binomial())

summary(mod0)
```

## Ridge 
```{r Ridge Model}
response <- "TenYearCHD"
features <- names(df_complete)[!names(df_complete) %in% c("TenYearCHD")]

df_complete["education"] <- factor(df_complete$education, labels = c("None", "HighSchool", "Collage", "Grad"))

X <- model.matrix(~.-1, df_complete[features])
y <- df_complete[response]

train_frac = 0.8
train.ind <- sample(c(TRUE, FALSE), nrow(df_complete),
                    replace=TRUE, prob=c(train_frac, 1-train_frac))

X_train <- X[train.ind,]
X_test <- X[!train.ind,]

y_train <- y[train.ind,]
y_test <- y[!train.ind,]

ridge_cv <- cv.glmnet(X_train, y_train, family = "binomial", alpha = 0)

plot(ridge_cv)
lambda_min = ridge_cv$lambda.min
lambda_1se = ridge_cv$lambda.1se
cat("Lambda min:", lambda_min, "\n")
cat("Lambda 1se:", lambda_1se)


print(ridge_cv)
coef(ridge_cv, s = "lambda.1se")
```
Make a fit with the best lambda and measuring error
```{r}
ridge_fit = glmnet(X_train, y_train, lambda = lambda_min, alpha = 0, family = "binomial")
ridge_pred = predict(ridge_fit, X_test, type = "class")

ridge_pred_class = factor(round(ridge_pred))
y_test <- factor(y_test)

conf_mat <- confusionMatrix(ridge_pred_class, y_test)
conf_mat

mse_ridge = mean((ridge_pred - y_test)^2)
mse_ridge
```

